### ISSUE TITLE
自动求和计算 feat

### ISSUE THREAD

**Issue by kongminhao** [xiaopc/qdii-value#1]
快点干活。少偷懒。

**Comment by xiaopc** [comment]
你套个 Excel 不就完了😾

**Comment by kongminhao** [comment]
不要，我不想装Excel

**Comment by kongminhao** [comment]
凭啥 wontfix, 坏逼。

**Comment by xiaopc** [comment]
自动获取持仓然后匹配感觉布星
准备搞成 gui 用户自己输入持仓
这个 repo 可能就 archive 掉了，所以就 wontfix 了啦啦啦啦啦啦
