### ISSUE TITLE
老哥！稳啊  我在 基金上看到找过来的

### ISSUE THREAD

**Issue by Ae86fast** [xiaopc/qdii-value#2]

**Comment by xiaopc** [comment]
感谢支持:smile:

**Comment by fujixpro3** [comment]
大佬🐂🍺 希望可以多加一些qdii基金

**Comment by vinthony** [comment]
Hi, 请问有online的demo嘛

**Comment by xiaopc** [comment]
> Hi, 请问有online的demo嘛

见 README

**Comment by vinthony** [comment]
> > Hi, 请问有online的demo嘛
> 
> 见 README

不好意思没说清楚，有没网页版的链接呀

**Comment by xiaopc** [comment]
有一个[临时 demo](https://jp-tok.functions.appdomain.cloud/api/v1/web/66a95783-5d4d-44d7-ac52-2bbeef6480b1/default/fund)，不保证维护
和 bot 大致一样

**Comment by vinthony** [comment]
好的 谢谢大佬！
