### ISSUE TITLE
ModuleNotFoundError: No module named 'qdii_value'

### ISSUE THREAD

**Issue by zhantaotao** [xiaopc/qdii-value#4]
在命令窗口和python中运行，比如输入“qdii-value 270023”，会出现ModuleNotFoundError: No module named 'qdii_value'问题。

**Comment by zhantaotao** [comment]
在本地文件夹中运行后，仍出现ModuleNotFoundError: No module named 'backports.zoneinfo'问题。

**Comment by zhantaotao** [comment]
应该是安装过程中出现“warning: install_lib: 'build\lib' does not exist -- no Python modules to install”导致的。可能是包文件夹中缺少 _init__.py 文件。

**Comment by xiaopc** [comment]
是用哪种方式安装的？
因为最开始命名的问题，仓库名字和包名不一样（仓库名字是`-`，包名是`_`）
如果是用 `pip install qdii-value` 安装的话是安装不上的
这个问题需要改动仓库名，暂时先不准备修复

`backports.zoneinfo` 可能是 Python 版本问题？因为 Python 3.6+ 会自带 `zoneinfo`

**Comment by zhantaotao** [comment]
你好，我是直接下载了安装包然后利用python setup.py install本地安装的。我发现我已经安装了backports.zoneinfo，但不知道为什么还提示
&nbsp; File "D:\Anaconda3\lib\site-packages\tzlocal-3.0b1-py3.7.egg\tzlocal\win32.py", line 14, in <module&gt;
&nbsp;&nbsp;&nbsp; from backports.zoneinfo import ZoneInfo, ZoneInfoNotFoundError
ModuleNotFoundError: No module named 'backports.zoneinfo'。


我是新手，不知道我用的对不对，烦请赐教，谢谢。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaopc/qdii-value"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月5日(星期五) 中午11:36
收件人:&nbsp;"xiaopc/qdii-value"<qdii-value@noreply.github.com&gt;;
抄送:&nbsp;"zhantaotao"<zhantaotao@stu.xjtu.edu.cn&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaopc/qdii-value] ModuleNotFoundError: No module named 'qdii_value' (#4)





 
是用哪种方式安装的？
 因为最开始命名的问题，仓库名字和包名不一样（仓库名字是-，包名是_）
 如果是用 pip install qdii-value 安装的话是安装不上的
 这个问题需要改动仓库名，暂时先不准备修复
 
backports.zoneinfo 可能是 Python 版本问题？因为 Python 3.6+ 会自带 zoneinfo

**Comment by xiaopc** [comment]
刚刚搜了下，用到的有些包不支持 Windows 环境
已经在改了:cry:

**Comment by zhantaotao** [comment]
十分感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaopc/qdii-value"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月5日(星期五) 中午12:46
收件人:&nbsp;"xiaopc/qdii-value"<qdii-value@noreply.github.com&gt;;
抄送:&nbsp;"zhantaotao"<zhantaotao@stu.xjtu.edu.cn&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaopc/qdii-value] ModuleNotFoundError: No module named 'qdii_value' (#4)





 
刚刚搜了下，用到的有些包不支持 Windows 环境
 已经在改了😢

**Comment by xiaopc** [comment]
修复了
