### ISSUE TITLE
backports.zoneinfo在windows上使用需要额外安装tzdata

### ISSUE THREAD

**Issue by zhantaotao** [xiaopc/qdii-value#5]
在windows上使用时，就算已经安装了backports.zoneinfo，仍会提示模块丢失。通过pip install tzdata额外安装tzdata后该程序可正常使用。

**Comment by xiaopc** [comment]
依赖的 [tzlocal](https://github.com/regebro/tzlocal) 这个库在后续版本 (>=3.0b) 才会补上这个依赖
不过部分 Windows 的 CPython 版本上没有这个问题
README 在改了

**Comment by zhantaotao** [comment]
你好，我还有最后一个问题，c = Config(json_conf_as_an_object)里面的json_conf_as_an_object是什么，比如我已经通过命令窗口建立了270023.json文件，应该如何利用config调用？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaopc/qdii-value"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月6日(星期六) 上午10:16
收件人:&nbsp;"xiaopc/qdii-value"<qdii-value@noreply.github.com&gt;;
抄送:&nbsp;"zhantaotao"<zhantaotao@stu.xjtu.edu.cn&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaopc/qdii-value] backports.zoneinfo在windows上使用需要额外安装tzdata (#5)





 
Closed #5.

**Comment by xiaopc** [comment]
把 JSON 反序列化为对象
示例代码：
```python
import json
from qdii_value.confs import Config
with open('270023.json', 'r') as f:
    obj = json.loads(f.read())
    conf = Config(obj)
```
`Config`  类目前只是对 JSON 配置文件做版本检查，没有其他作用

**Comment by zhantaotao** [comment]
收到，十分感谢！



---原始邮件---
发件人: "xiaopc"<notifications@github.com&gt;
发送时间: 2021年2月6日(周六) 中午11:07
收件人: "xiaopc/qdii-value"<qdii-value@noreply.github.com&gt;;
抄送: "zhantaotao"<zhantaotao@stu.xjtu.edu.cn&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [xiaopc/qdii-value]backports.zoneinfo在windows上使用需要额外安装tzdata (#5)




 
把 JSON 反序列化为对象
 示例代码：
 import json from qdii_value.confs import Config with open('270023.json', 'r') as f:     obj = json.loads(f.read())     conf = Config(obj)
 
Config  类目前只是对 JSON 配置文件做版本检查，没有其他作用
