### ISSUE TITLE
可以自己部署在freebsd上吗？

### ISSUE THREAD

**Issue by ricky0829** [xiaopc/qdii-value#8]
看了下大佬的readme，好像是可以私有部署的，不过不想部署在Windows上，家里刚好有个freenas可以用。但感觉好像只是后台程序的部署，不包括网页的哈？

**Comment by xiaopc** [comment]
本项目只包括基础框架和命令行界面部分，Web 服务可以根据基础框架进行设计。
安装后可以连接 SSH 运行，不过有些依赖没有测试在 FreeBSD 下的兼容性。
后面可能会整理出生成持仓表图片的 Python Web 简单示例。

**Comment by ricky0829** [comment]
感谢回复，命令行自己用也够了
