### ISSUE TITLE
补充一个摩根持仓提供方（5.31 前会公布 100% 持仓）

### ISSUE THREAD

**Issue by ricky0829** [xiaopc/qdii-value#9]
首先感谢大佬
本来想电报联系反馈，但看佬上线时间是最近一个月，可能无法及时看到，所以在这里提一下，不合适的话请佬删除
补充的提供方：**摩根官网：https://www.cifm.com/fund/968061/** ，在公告及提示里，每个月底会公布上个月的最新 Top10 持仓（产品单页），还会定期公布半年度报告、年度报告，而这两份报告里会公布 100% 的持仓

以 968061 为例，investing 的持仓和摩根官网发布的基金月报里最近三个月的版本都不符，不知道 investing 的数据是否是最新的，可以在下次公布月报时进行核对
![image](https://github.com/xiaopc/qdii-value/assets/28993319/bcad8b70-dc15-43bc-aefb-4da45bf48da5)

![image](https://github.com/xiaopc/qdii-value/assets/28993319/49c18943-2edc-475a-912a-bf0731ba0751)

另外根据摩根的公告，5.31 前会公布半年度报告，里面会有 100% 持仓，届时可以更新一下估值模型的持仓

**Comment by xiaopc** [comment]
qdii.in 相关可以在置顶公告那里发
四月底公布的三月产品单页是二月底的持仓，时效性有点晚；晨星数据向各代销银行提供的的比较新，但是找不到香港市场能免费看的渠道
